import type { Topic } from "./types.js";

export const TOPICS: Topic[] = [
  // Social/Ethical
  {
    id: "social-media-age-limit",
    title: "Social media age limits",
    proposition: "Social media platforms should be banned for users under 18",
    category: "social",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["technology", "youth", "mental health", "regulation"],
  },
  {
    id: "ai-in-schools",
    title: "AI in education",
    proposition: "AI tools like ChatGPT should be permitted and integrated into school curricula",
    category: "social",
    ageGroup: "teens",
    difficulty: "medium",
    tags: ["AI", "education", "technology"],
  },
  {
    id: "mandatory-voting",
    title: "Mandatory voting",
    proposition: "Voting should be compulsory for all eligible citizens",
    category: "social",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["democracy", "civic duty", "rights"],
  },
  {
    id: "universal-basic-income",
    title: "Universal Basic Income",
    proposition: "Every citizen should receive a guaranteed monthly income from the government regardless of employment status",
    category: "social",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["economics", "welfare", "automation"],
  },
  {
    id: "four-day-work-week",
    title: "Four-day work week",
    proposition: "The standard work week should be reduced to four days without a reduction in pay",
    category: "social",
    ageGroup: "general",
    difficulty: "easy",
    tags: ["work", "economics", "wellbeing"],
  },
  {
    id: "smartphone-ban-schools",
    title: "Smartphones in schools",
    proposition: "Smartphones should be banned in schools during school hours",
    category: "social",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["technology", "education", "youth"],
  },
  {
    id: "drug-decriminalization",
    title: "Drug decriminalization",
    proposition: "Personal drug use should be decriminalized and treated as a public health issue rather than a criminal one",
    category: "social",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["drugs", "criminal justice", "public health"],
  },
  {
    id: "affirmative-action",
    title: "Affirmative action",
    proposition: "Universities should use race as a factor in admissions decisions to promote diversity",
    category: "social",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["education", "race", "equity"],
  },

  // Science/Environment
  {
    id: "nuclear-energy",
    title: "Nuclear energy",
    proposition: "Nuclear power should be a central part of the strategy to combat climate change",
    category: "science",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["energy", "climate", "environment"],
  },
  {
    id: "lab-grown-meat",
    title: "Lab-grown meat",
    proposition: "Governments should actively subsidize and promote lab-grown meat as a climate solution",
    category: "science",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["food", "environment", "technology"],
  },
  {
    id: "geoengineering",
    title: "Geoengineering",
    proposition: "Scientists should be permitted to conduct geoengineering experiments to combat climate change",
    category: "science",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["climate", "science", "technology"],
  },
  {
    id: "gmos",
    title: "Genetically modified organisms",
    proposition: "GMO foods should be embraced and promoted as a solution to global food security",
    category: "science",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["food", "science", "agriculture"],
  },
  {
    id: "animal-testing",
    title: "Animal testing",
    proposition: "Animal testing for medical research should be banned in favor of alternative methods",
    category: "science",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["animals", "ethics", "medicine"],
  },
  {
    id: "space-exploration",
    title: "Space exploration funding",
    proposition: "Governments should invest more in space exploration rather than focusing solely on Earth's problems",
    category: "science",
    ageGroup: "general",
    difficulty: "easy",
    tags: ["space", "science", "economics"],
  },
  {
    id: "carbon-tax",
    title: "Carbon tax",
    proposition: "A national carbon tax is the most effective policy tool to reduce greenhouse gas emissions",
    category: "science",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["climate", "economics", "policy"],
  },

  // Politics/Policy
  {
    id: "school-uniforms",
    title: "School uniforms",
    proposition: "All public schools should require students to wear uniforms",
    category: "policy",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["education", "identity", "equality"],
  },
  {
    id: "standardized-testing",
    title: "Standardized testing",
    proposition: "Standardized testing should be abolished as a measure of student and school performance",
    category: "policy",
    ageGroup: "teens",
    difficulty: "medium",
    tags: ["education", "assessment", "equity"],
  },
  {
    id: "prison-reform",
    title: "Prison reform",
    proposition: "The primary goal of the prison system should be rehabilitation rather than punishment",
    category: "policy",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["criminal justice", "rehabilitation", "society"],
  },
  {
    id: "gun-control",
    title: "Gun control",
    proposition: "The government should impose strict regulations on the sale and ownership of firearms",
    category: "policy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["guns", "rights", "safety"],
  },
  {
    id: "voting-age",
    title: "Voting age",
    proposition: "The voting age should be lowered to 16",
    category: "policy",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["democracy", "youth", "civic engagement"],
  },
  {
    id: "death-penalty",
    title: "Death penalty",
    proposition: "Capital punishment should be abolished in all countries",
    category: "policy",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["criminal justice", "ethics", "human rights"],
  },
  {
    id: "immigration-policy",
    title: "Open borders",
    proposition: "Countries should move toward open borders and allow free movement of people",
    category: "policy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["immigration", "economics", "human rights"],
  },
  {
    id: "free-college",
    title: "Free higher education",
    proposition: "University education should be free for all citizens",
    category: "policy",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["education", "economics", "equality"],
  },

  // Philosophy/Values
  {
    id: "ai-consciousness",
    title: "AI consciousness",
    proposition: "Sufficiently advanced AI systems should be granted legal rights and moral consideration",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["AI", "ethics", "consciousness"],
  },
  {
    id: "trolley-problem",
    title: "Trolley problem variant",
    proposition: "It is morally permissible to harm one person to save five others",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["ethics", "utilitarianism", "philosophy"],
  },
  {
    id: "free-speech-limits",
    title: "Free speech limits",
    proposition: "Hate speech should be legally prohibited even if it restricts free expression",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["free speech", "hate speech", "rights"],
  },
  {
    id: "euthanasia",
    title: "Euthanasia",
    proposition: "Physician-assisted dying should be legal for terminally ill patients who request it",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["death", "autonomy", "medicine"],
  },
  {
    id: "vegetarianism",
    title: "Meat consumption ethics",
    proposition: "Eating meat is ethically indefensible given our current knowledge about animal suffering",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["animals", "ethics", "food"],
  },
  {
    id: "privacy-vs-security",
    title: "Privacy vs. national security",
    proposition: "Governments should be permitted to conduct mass surveillance to prevent terrorism",
    category: "philosophy",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["privacy", "security", "rights"],
  },

  // Technology
  {
    id: "self-driving-cars",
    title: "Self-driving cars",
    proposition: "Self-driving cars should be permitted on public roads before they are proven safer than human drivers",
    category: "technology",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["technology", "safety", "innovation"],
  },
  {
    id: "data-privacy",
    title: "Data privacy vs. convenience",
    proposition: "Users should accept reduced privacy in exchange for more personalized and convenient digital services",
    category: "technology",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["privacy", "technology", "data"],
  },
  {
    id: "video-game-violence",
    title: "Video game violence",
    proposition: "Violent video games contribute to real-world violent behavior in players",
    category: "technology",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["games", "violence", "youth"],
  },
  {
    id: "social-media-algorithms",
    title: "Social media algorithms",
    proposition: "Social media companies should be legally required to use chronological feeds instead of algorithmic ones",
    category: "technology",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["social media", "algorithms", "regulation"],
  },
  {
    id: "cryptocurrency",
    title: "Cryptocurrency",
    proposition: "Governments should ban or heavily regulate cryptocurrencies",
    category: "technology",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["crypto", "economics", "regulation"],
  },
  {
    id: "ai-art",
    title: "AI-generated art",
    proposition: "AI-generated artwork should be eligible for copyright protection",
    category: "technology",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["AI", "art", "copyright"],
  },
  {
    id: "remote-work",
    title: "Remote work",
    proposition: "Companies should offer permanent remote work options to all employees who can perform their jobs remotely",
    category: "technology",
    ageGroup: "general",
    difficulty: "easy",
    tags: ["work", "technology", "productivity"],
  },

  // Historical/Counterfactual
  {
    id: "colonialism-reparations",
    title: "Colonial reparations",
    proposition: "Former colonial powers should pay reparations to the countries they colonized",
    category: "historical",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["history", "justice", "economics"],
  },
  {
    id: "hiroshima",
    title: "Hiroshima bombing",
    proposition: "The United States was morally justified in dropping atomic bombs on Hiroshima and Nagasaki",
    category: "historical",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["history", "war", "ethics"],
  },
  {
    id: "statues-removal",
    title: "Historical statues",
    proposition: "Statues of historical figures who held views we now consider immoral should be removed from public spaces",
    category: "historical",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["history", "culture", "values"],
  },
  {
    id: "columbus",
    title: "Columbus Day",
    proposition: "Columbus Day should be replaced by Indigenous Peoples Day in all countries that celebrate it",
    category: "historical",
    ageGroup: "general",
    difficulty: "easy",
    tags: ["history", "culture", "Indigenous"],
  },
  {
    id: "vietnam-war",
    title: "Vietnam War",
    proposition: "US involvement in the Vietnam War was morally and strategically unjustified",
    category: "historical",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["history", "war", "US politics"],
  },

  // Economics
  {
    id: "minimum-wage",
    title: "Minimum wage increase",
    proposition: "The minimum wage should be significantly raised and indexed to inflation",
    category: "economics",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["economics", "wages", "inequality"],
  },
  {
    id: "wealth-tax",
    title: "Wealth tax",
    proposition: "Billionaires should be taxed heavily enough to prevent the concentration of extreme wealth",
    category: "economics",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["economics", "inequality", "taxation"],
  },
  {
    id: "free-trade",
    title: "Free trade vs. protectionism",
    proposition: "Countries should pursue free trade agreements rather than protecting domestic industries",
    category: "economics",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["economics", "trade", "globalization"],
  },
  {
    id: "rent-control",
    title: "Rent control",
    proposition: "Rent control policies effectively make housing more affordable for low-income residents",
    category: "economics",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["housing", "economics", "policy"],
  },

  // Health
  {
    id: "vaccine-mandate",
    title: "Vaccine mandates",
    proposition: "Governments should mandate COVID-19 and other vaccines for all citizens without medical exemptions",
    category: "health",
    ageGroup: "general",
    difficulty: "hard",
    tags: ["health", "rights", "public health"],
  },
  {
    id: "junk-food-tax",
    title: "Junk food taxes",
    proposition: "Governments should impose significant taxes on unhealthy foods to combat obesity",
    category: "health",
    ageGroup: "general",
    difficulty: "medium",
    tags: ["health", "policy", "economics"],
  },
  {
    id: "mental-health-schools",
    title: "Mental health education",
    proposition: "Mental health education should be a mandatory subject in all schools from primary level",
    category: "health",
    ageGroup: "teens",
    difficulty: "easy",
    tags: ["mental health", "education", "youth"],
  },
];

export function getTopicsByCategory(category?: string): Topic[] {
  if (!category) return TOPICS;
  return TOPICS.filter(t => t.category === category);
}

export function getTopicsByAgeGroup(ageGroup?: string): Topic[] {
  if (!ageGroup) return TOPICS;
  return TOPICS.filter(t => t.ageGroup === ageGroup || t.ageGroup === "general");
}

export function filterTopics(category?: string, ageGroup?: string): Topic[] {
  let topics = TOPICS;
  if (category) topics = topics.filter(t => t.category === category);
  if (ageGroup) topics = topics.filter(t => t.ageGroup === ageGroup || t.ageGroup === "general");
  return topics;
}

export const CATEGORIES = [...new Set(TOPICS.map(t => t.category))];
export const AGE_GROUPS = [...new Set(TOPICS.map(t => t.ageGroup))];
